#!/bin/sh

set -e

if [ "$1" = "purge" ]
then
	rm -rf /var/cache/google-android-build-tools-installer
	if [ -e /usr/share/debconf/confmodule ]
	then
		# Source debconf library.
		. /usr/share/debconf/confmodule
		# Unregister the package
		if db_get google-android-installers/mirror; then
			db_unregister google-android-installers/mirror
		fi
	fi
fi

#DEBHELPER#

exit 0

