#!/bin/sh

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_get google-android-build-tools-installer/mirror

case "$1" in
    configure)
        mkdir -p /var/cache/google-android-build-tools-installer
        cp /usr/share/google-android-build-tools-installer/Makefile \
            /usr/share/google-android-build-tools-installer/build-tools_r23.0.3-linux.zip.sha1 \
            /var/cache/google-android-build-tools-installer/
        make -C /var/cache/google-android-build-tools-installer/ DL_MIRROR="$RET" install
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0


