#!/bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
        make -C /usr/share/google-android-build-tools-installer uninstall
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0


